/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

/**
 *
 * @author Etijah
 */
import javax.swing.*;
import java.awt.event.ActionEvent;

public class notificationItem extends javax.swing.JPanel {

    /**
     * Creates new form notificationItem
     */
    private String photo;
    private String username;
    private String desc;
    private String time;
    private int type;
    public notificationItem(String photo,String username,String desc,String time,int type) {
        this.photo = photo;
        this.username = username;
        this.desc = desc;
        this.time = time;
        this.type = type;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        TimeLabel = new javax.swing.JLabel();
        VIewOrAcceptButton = new javax.swing.JButton();
        RejectButton = new javax.swing.JButton();
        imageAvatar1 = new frontend.notificationsUI.ImageAvatar();

        usernameLabel.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(90, 90, 90));
        usernameLabel.setText("username");

        descriptionLabel.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(153, 153, 153));
        descriptionLabel.setText("description");

        TimeLabel.setForeground(new java.awt.Color(50, 50, 50));
        TimeLabel.setText("Time");

        VIewOrAcceptButton.setText("View Group");

        RejectButton.setText("Reject");

        imageAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/behance-profile.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VIewOrAcceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RejectButton))
                    .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(imageAvatar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usernameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descriptionLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(VIewOrAcceptButton)
                                .addComponent(RejectButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TimeLabel)))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    void loadNotification()
    {
        imageAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/behance-profile.png")));
        usernameLabel.setText(username);
        descriptionLabel.setText(desc);
        TimeLabel.setText(time);
        if(type == 1)
        {
            VIewOrAcceptButton.setText("Accept");
            VIewOrAcceptButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    VIewOrAcceptButtonActionPerformed(evt);
                }
                private void VIewOrAcceptButtonActionPerformed(ActionEvent evt) {

                }
            });
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RejectButton;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JButton VIewOrAcceptButton;
    private javax.swing.JLabel descriptionLabel;
    private frontend.notificationsUI.ImageAvatar imageAvatar1;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
