/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Signup;
import backend.Validations;

import java.awt.*;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Mazen
 */
public class SignUpPage extends javax.swing.JFrame {
    private boolean PassWordHidden = true;
    /**
     * Creates new form SignUpPage
     */
    WelcomePage welcomePage;
    public SignUpPage(WelcomePage welcomePage) {
        initComponents();
        setLocationRelativeTo(null);
        this.welcomePage = welcomePage;
        setTitle("Sign Up");
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        Male.setActionCommand("Male");
        Female.setActionCommand("Female");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //button group allows one button only to be active
        buttonGroup1.add(Male);
        buttonGroup1.add(Female);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        signUpButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Female = new javax.swing.JRadioButton();
        Male = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        userNameTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        showPasswordButton = new javax.swing.JButton();
        retypePasswordTxt = new javax.swing.JPasswordField();
        passWordText = new javax.swing.JPasswordField();
        DOBcalendar = new de.wannawork.jcalendar.JCalendarComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up");
        setSize(500, 600);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(244, 244, 244));  // Background color

        signUpButton.setText("Sign Up");
        signUpButton.setBackground(new java.awt.Color(62, 142, 65));  // Button background color
        signUpButton.setForeground(Color.WHITE);
        signUpButton.setFont(new Font("Arial", Font.BOLD, 14));
        signUpButton.setBorderPainted(false);
        signUpButton.setFocusPainted(false);
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    signUpButtonActionPerformed(evt);
                } catch (NoSuchAlgorithmException | IOException e) {
                    e.printStackTrace();
                }
            }
        });

        jLabel1.setText("User Name");
        jLabel1.setFont(new Font("Arial", Font.PLAIN, 14));

        jLabel2.setText("Gender");
        jLabel2.setFont(new Font("Arial", Font.PLAIN, 14));

        jLabel3.setText("Email");
        jLabel3.setFont(new Font("Arial", Font.PLAIN, 14));

        jLabel4.setText("Password");
        jLabel4.setFont(new Font("Arial", Font.PLAIN, 14));

        Female.setText("Female");
        Male.setText("Male");
        buttonGroup1.add(Male);
        buttonGroup1.add(Female);

        jLabel5.setText("Date of Birth");
        jLabel5.setFont(new Font("Arial", Font.PLAIN, 14));

        jLabel6.setText("Retype Password");
        jLabel6.setFont(new Font("Arial", Font.PLAIN, 14));

        showPasswordButton.setText("Show Password");
        showPasswordButton.setFont(new Font("Arial", Font.PLAIN, 12));
        showPasswordButton.setBackground(new java.awt.Color(200, 200, 200));
        showPasswordButton.setFocusPainted(false);
        showPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordButtonActionPerformed(evt);
            }
        });

        // Input field design
        emailTxt.setBackground(new java.awt.Color(255, 255, 255));
        emailTxt.setBorder(BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 1));
        emailTxt.setFont(new Font("Arial", Font.PLAIN, 14));

        userNameTxt.setBackground(new java.awt.Color(255, 255, 255));
        userNameTxt.setBorder(BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 1));
        userNameTxt.setFont(new Font("Arial", Font.PLAIN, 14));

        passWordText.setBackground(new java.awt.Color(255, 255, 255));
        passWordText.setBorder(BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 1));
        passWordText.setFont(new Font("Arial", Font.PLAIN, 14));

        retypePasswordTxt.setBackground(new java.awt.Color(255, 255, 255));
        retypePasswordTxt.setBorder(BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 1));
        retypePasswordTxt.setFont(new Font("Arial", Font.PLAIN, 14));

        DOBcalendar.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(userNameTxt))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(emailTxt))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(passWordText))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(retypePasswordTxt))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(DOBcalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(showPasswordButton))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Male)
                                                .addGap(18, 18, 18)
                                                .addComponent(Female))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(100, 100, 100)))
                                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(Male)
                                        .addComponent(Female))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(passWordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(showPasswordButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(retypePasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(DOBcalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(signUpButton)
                                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }


    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleActionPerformed

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleActionPerformed

    private void showPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordButtonActionPerformed
         if(!(PassWordHidden=!PassWordHidden)){
         passWordText.setEchoChar('\0');
         retypePasswordTxt.setEchoChar('\0');
         }else{
         passWordText.setEchoChar('*');
         retypePasswordTxt.setEchoChar('*');
         }
    }//GEN-LAST:event_showPasswordButtonActionPerformed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) throws NoSuchAlgorithmException, IOException, IOException {//GEN-FIRST:event_signUpButtonActionPerformed

        String userName = userNameTxt.getText().trim().replace("\n","");


        String email = emailTxt.getText().trim().replace("\n","");
        String password = new String(passWordText.getPassword()).trim();
        String reTypePassword = new String(retypePasswordTxt.getPassword()).trim();
        LocalDate dob = DOBcalendar.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        if(userName.isEmpty()||buttonGroup1.getSelection()==null||email.isEmpty()||password.isEmpty()||reTypePassword.isEmpty()){
            //any missing data entry
            JOptionPane.showMessageDialog(null,"Please Fill All Fields to signup!" ,"empty fields",JOptionPane.ERROR_MESSAGE);
            return;
        }

            String gender = buttonGroup1.getSelection().getActionCommand();
            //this line could cause nullptr exception so put it after checking getSelection doesn't return null

            if(!password.equals(reTypePassword)){
            JOptionPane.showMessageDialog(null,"Please make sure password matches reentered password!" ,"password",JOptionPane.ERROR_MESSAGE);
            return ;
            }
            if(!Validations.validateName(userName)){
                JOptionPane.showMessageDialog(null,"Please enter a valid name!" ,"name error",JOptionPane.ERROR_MESSAGE);
                return ;
            }
            if(!Validations.validatePassword(password)){
                JOptionPane.showMessageDialog(null,"the password should contain 8 characters at least, one alphabet , one symbol" ,"password error",JOptionPane.ERROR_MESSAGE);
                return ;
            }
            if(!Validations.validateEmailFormat(email)){
                JOptionPane.showMessageDialog(null,"Please enter a valid email format!" ,"email error",JOptionPane.ERROR_MESSAGE);
                return;
            }
            //trying to signup
            Signup s=Signup.getInstance();
            if(s.signup(userName, email, password, gender, dob))
            {
        JOptionPane.showMessageDialog(null, "Successful Signup,please wait");
        s.save();
        setVisible(false);

        welcomePage.setVisible(true);
        dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"this Email already existed","Error",JOptionPane.ERROR_MESSAGE);
            }

    }//GEN-LAST:event_signUpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpPage(new WelcomePage()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.wannawork.jcalendar.JCalendarComboBox DOBcalendar;
    private javax.swing.JRadioButton Female;
    private javax.swing.JRadioButton Male;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField passWordText;
    private javax.swing.JPasswordField retypePasswordTxt;
    private javax.swing.JButton showPasswordButton;
    private javax.swing.JButton signUpButton;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
