package frontend;

import javax.swing.*;

public class StoryDisplayer extends javax.swing.JFrame {

    private String thumbnailPhoto;
    private String content;

    /**
     * Creates new form StoryDisplayer
     */
    public StoryDisplayer(String thumbnailPhoto, String content) {
        initComponents();
        this.thumbnailPhoto = thumbnailPhoto;
        this.content = content;
        setLocationRelativeTo(null);
        setTitle("story displayer");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Dynamically add the thumbnail and content
        setupStoryDisplay();
    }

    private void setupStoryDisplay() {
        // Set layout for the frame
        setLayout(new BoxLayout(getContentPane(), BoxLayout.Y_AXIS));

        // Add the thumbnail photo
        JLabel thumbnailLabel = new JLabel();
        thumbnailLabel.setIcon(new ImageIcon(thumbnailPhoto)); // Set the image as an icon
        thumbnailLabel.setAlignmentX(CENTER_ALIGNMENT);
        add(thumbnailLabel);

        // Add the content if it exists
        if (content != null && !content.isEmpty()) {
            JLabel contentLabel = new JLabel("<html>" + content.replace("\n", "<br>") + "</html>");
            contentLabel.setAlignmentX(CENTER_ALIGNMENT);
            add(contentLabel);
        }

        // Adjust the frame size
        pack();
        setLocationRelativeTo(null); // Center the frame on the screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Sample thumbnail path and content
        String thumbnailPath = "path/to/thumbnail.jpg"; // Update with the actual path
        String storyContent = "This is the content of the story. If empty, it won't be displayed.";

        // Create and display the story displayer
        java.awt.EventQueue.invokeLater(() -> new StoryDisplayer(thumbnailPath, storyContent).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
